// Function metadata powering IntelliSense suggestions for DIPS Arena calc expressions.
// Based on DIPS Form Designer v2 function documentation.
const FUNCTION_ITEMS = [
  // === Age and Duration Functions ===
  { name: 'AGE', signature: 'AGE(birthdate_ticks, current_date_ticks)', detail: 'Calculates age based on birth date and a given date.' },
  { name: 'DURATION_ADD', signature: 'DURATION_ADD(iso8601_date, iso8601_duration)', detail: 'Adds the given ISO8601 Duration text to the given ISO8601 DateTime or ISO8601 Date string.' },
  { name: 'DURATION_SUBTRACT', signature: 'DURATION_SUBTRACT(iso8601_date, iso8601_duration)', detail: 'Subtracts the given ISO8601 Duration text from the given ISO8601 DateTime or ISO8601 Date string.' },
  { name: 'DURATION_TO_DAYS', signature: 'DURATION_TO_DAYS(iso8601_duration_text)', detail: 'Returns the numeric value of the duration in days.' },
  { name: 'DURATION_TO_HOURS', signature: 'DURATION_TO_HOURS(iso8601_duration_text)', detail: 'Returns the numeric value of the duration in hours.' },
  { name: 'DURATION_TO_MINUTES', signature: 'DURATION_TO_MINUTES(iso8601_duration_text)', detail: 'Returns the numeric value of the duration in minutes.' },
  { name: 'DURATION_TO_SECONDS', signature: 'DURATION_TO_SECONDS(iso8601_duration_text)', detail: 'Returns the numeric value of the duration in seconds.' },
  { name: 'ISO8601DURATION', signature: 'ISO8601DURATION(date_text1, date_text2)', detail: 'Calculates the difference between two dates. The result is returned as an ISO 8601 duration string.' },
  { name: 'DURATIONTICKS', signature: 'DURATIONTICKS(duration)', detail: 'Converts an ISO8601 duration (string) to ticks.' },

  // === Date and Time Functions ===
  { name: 'NOW', signature: 'NOW()', detail: 'Returns datetime representing the current date and time.' },
  { name: 'TODAY', signature: 'TODAY()', detail: 'Returns datetime representing today\'s date.' },
  { name: 'NOWTICKS', signature: 'NOWTICKS()', detail: 'Returns the number of ticks representing the current datetime.' },
  { name: 'TODAYTICKS', signature: 'TODAYTICKS()', detail: 'Returns the number of ticks representing today\'s date.' },
  { name: 'DATEVALUE', signature: 'DATEVALUE(date_text)', detail: 'Converts an ISO 8601 date or datetime from string to ticks.' },
  { name: 'DAYTICKS', signature: 'DAYTICKS(days)', detail: 'Converts days to ticks.' },
  { name: 'HOURTICKS', signature: 'HOURTICKS(hours)', detail: 'Converts hours to ticks.' },
  { name: 'MINUTETICKS', signature: 'MINUTETICKS(minutes)', detail: 'Converts minutes to ticks.' },
  { name: 'DATETIME', signature: 'DATETIME(ticks)', detail: 'Converts ticks to datetime.' },
  { name: 'ISO8601DATETIME', signature: 'ISO8601DATETIME(ticks)', detail: 'Converts ticks to an ISO8601 datetime string.' },
  { name: 'ISO8601DATE', signature: 'ISO8601DATE(ticks)', detail: 'Converts ticks to an ISO8601 date string.' },
  { name: 'ISO8601TIME', signature: 'ISO8601TIME(ticks)', detail: 'Converts ticks to an ISO8601 time string.' },
  { name: 'FORMATDATETIME', signature: 'FORMATDATETIME(ticks, format, [language])', detail: 'Returns a formatted date. Ex: FORMATDATETIME(NOWTICKS(), "D", "en-us") returns "Thursday, October 6, 2016".' },
  { name: 'WEEKNUM', signature: 'WEEKNUM(ticks)', detail: 'Returns the week number of the year that includes the date in the specified datetime value represented by ticks.' },
  { name: 'DAYS', signature: 'DAYS(end_date, start_date)', detail: 'Returns the number of days between two dates.' },
  { name: 'HOURS', signature: 'HOURS(end_date, start_date)', detail: 'Returns the number of hours between two dates.' },
  { name: 'WEEKS', signature: 'WEEKS(end_date, start_date)', detail: 'Returns the number of weeks between two dates.' },
  { name: 'MONTH', signature: 'MONTH(ticks)', detail: 'Returns the month of a date represented as ticks. The month is returned as an integer from 1 (January) to 12 (December).' },
  { name: 'YEAR', signature: 'YEAR(ticks)', detail: 'Returns the year of a date represented by ticks. The year is returned as an integer in the range 0001-9999.' },

  // === Validation and Check Functions ===
  { name: 'ISBLANK', signature: 'ISBLANK(value)', detail: 'Checks whether a text string is empty or not. Returns true if empty, false if not.' },
  { name: 'ISNUMBER', signature: 'ISNUMBER(value)', detail: 'Checks whether a value is a number or not. Returns true if number, false if not.' },
  { name: 'ISNULL', signature: 'ISNULL(value)', detail: 'Checks whether the value is NULL. Returns true if NULL, false if not.' },
  { name: 'IFNULL', signature: 'IFNULL(expression, value_if_null)', detail: 'Checks if an expression is NULL, returns the result if not, or returns the expression you specify if NULL.' },
  { name: 'NULL', signature: 'NULL', detail: 'Returns NULL.' },
  { name: 'MATCHES', signature: 'MATCHES(regex, calcId)', detail: 'Allows you to specify exactly which characters you want to allow the user to enter in a field.' },

  // === Template Functions ===
  { name: 'TEMPLATEVARIABLE', signature: 'TEMPLATEVARIABLE("template_variable")', detail: 'Takes a template variable and displays it in the form. Ex: "Patient.FirstName".' },

  // === Statistical Functions ===
  { name: 'AVERAGE', signature: 'AVERAGE(number1, [number2], ...)', detail: 'Returns the average of the arguments.' },
  { name: 'AVERAGEA', signature: 'AVERAGEA(value1, [value2], ...)', detail: 'Returns the average of the arguments, including numbers, text, and logical values.' },
  { name: 'COUNT', signature: 'COUNT(value1, [value2], ...)', detail: 'Counts how many numbers are in the argument list.' },
  { name: 'COUNTA', signature: 'COUNTA(value1, [value2], ...)', detail: 'Counts the number of non-empty values in a range.' },
  { name: 'COUNTBLANK', signature: 'COUNTBLANK(value1, [value2], ...)', detail: 'Counts empty values in a specified range of values.' },
  { name: 'COUNTIF', signature: 'COUNTIF(value1, [value2], ..., criteria)', detail: 'Counts the number of values within a range that satisfy a single criterion you specify.' },
  { name: 'MAX', signature: 'MAX(number1, [number2], ...)', detail: 'Returns the maximum value in an argument list.' },
  { name: 'MAXA', signature: 'MAXA(value1, [value2], ...)', detail: 'Returns the maximum value in an argument list, including numbers, text, and logical values.' },
  { name: 'MIN', signature: 'MIN(number1, [number2], ...)', detail: 'Returns the minimum value in an argument list.' },
  { name: 'MINA', signature: 'MINA(value1, [value2], ...)', detail: 'Returns the minimum value in an argument list, including numbers, text, and logical values.' },
  { name: 'STDEV', signature: 'STDEV(number1, [number2], ...)', detail: 'Estimates standard deviation based on a sample.' },
  { name: 'STDEVA', signature: 'STDEVA(value1, [value2], ...)', detail: 'Estimates standard deviation based on a sample, including text and logical values.' },
  { name: 'STDEVP', signature: 'STDEVP(number1, [number2], ...)', detail: 'Calculates standard deviation based on the entire population given as arguments.' },
  { name: 'STDEVPA', signature: 'STDEVPA(value1, [value2], ...)', detail: 'Calculates standard deviation based on the entire population, including text and logical values.' },
  { name: 'VAR', signature: 'VAR(number1, [number2], ...)', detail: 'Estimates variance based on a sample.' },
  { name: 'VARA', signature: 'VARA(value1, [value2], ...)', detail: 'Estimates variance based on a sample, including text and logical values.' },
  { name: 'VARP', signature: 'VARP(number1, [number2], ...)', detail: 'Calculates variance based on the entire population.' },
  { name: 'VARPA', signature: 'VARPA(value1, [value2], ...)', detail: 'Calculates variance based on the entire population, including text and logical values.' },

  // === Text Functions ===
  { name: 'CHAR', signature: 'CHAR(number)', detail: 'Returns the character corresponding to the code number.' },
  { name: 'CODE', signature: 'CODE(text)', detail: 'Returns a numeric code for the first character in a text string.' },
  { name: 'CONCATENATE', signature: 'CONCATENATE(text1, [text2], ...)', detail: 'Joins up to 255 text strings into one text string.' },
  { name: 'FIND', signature: 'FIND(find_text, within_text, [start_position])', detail: 'Finds one text string inside another text string and returns the starting position.' },
  { name: 'LEFT', signature: 'LEFT(text, num_chars)', detail: 'Returns the first character or characters in a text string.' },
  { name: 'LEN', signature: 'LEN(text)', detail: 'Returns the number of characters in a text string.' },
  { name: 'LOWER', signature: 'LOWER(text)', detail: 'Converts uppercase letters to lowercase.' },
  { name: 'MID', signature: 'MID(text, start_position, num_chars)', detail: 'Returns a specified number of characters from a text string, starting from the position you specify.' },
  { name: 'PROPER', signature: 'PROPER(text)', detail: 'Capitalizes the first letter in a text string and converts the rest to lowercase.' },
  { name: 'REPLACE', signature: 'REPLACE(old_text, start_position, num_chars, new_text)', detail: 'Replaces part of a text string, based on the number of characters you specify, with a new text.' },
  { name: 'REPT', signature: 'REPT(text, number_times)', detail: 'Repeats text a given number of times.' },
  { name: 'RIGHT', signature: 'RIGHT(text, num_chars)', detail: 'Returns the last characters in a text string, based on the number of characters you specify.' },
  { name: 'SEARCH', signature: 'SEARCH(find_text, within_text, [start_position])', detail: 'Finds one text value within another (case-insensitive).' },
  { name: 'SUBSTITUTE', signature: 'SUBSTITUTE(text, old_text, new_text, [instance_num])', detail: 'Substitutes old_text with new_text in a text string.' },
  { name: 'T', signature: 'T(value)', detail: 'Returns the text referred to by value.' },
  { name: 'TEXT', signature: 'TEXT(value, [format_text])', detail: 'Converts a numeric value to text and lets you specify the display formatting.' },
  { name: 'TRIM', signature: 'TRIM(text)', detail: 'Removes all spaces from text except for single spaces between words.' },
  { name: 'UPPER', signature: 'UPPER(text)', detail: 'Converts text to uppercase.' },
  { name: 'VALUE', signature: 'VALUE(text)', detail: 'Converts a text string representing a number to a number.' },

  // === Lookup and Reference Functions ===
  { name: 'CHOOSE', signature: 'CHOOSE(index, value1, [value2], ...)', detail: 'Uses index to return a value from the list of arguments. Ex: CHOOSE(2, "a", "b", "c") returns "b".' },
  { name: 'ANY', signature: 'ANY(type, find_text, within_text1, [within_text2], ...)', detail: 'Returns a value indicating whether a specified substring occurs within this string or one or more strings in a list. type = [startswith, endswith, equals, contains]' },
  { name: 'ALL', signature: 'ALL(type, find_text, within_text1, [within_text2], ...)', detail: 'Returns a value indicating whether a specified substring occurs within this string or within every string in a list. type = [startswith, endswith, equals, contains]' },

  // === Mathematical Functions ===
  { name: 'ABS', signature: 'ABS(number)', detail: 'Returns the absolute value of a number.' },
  { name: 'ACOS', signature: 'ACOS(number)', detail: 'Returns the arccosine of a number.' },
  { name: 'ASIN', signature: 'ASIN(number)', detail: 'Returns the arcsine of a number.' },
  { name: 'ATAN', signature: 'ATAN(number)', detail: 'Returns the arctangent of a number.' },
  { name: 'ATAN2', signature: 'ATAN2(x_num, y_num)', detail: 'Returns the arctangent from x and y coordinates.' },
  { name: 'CEILING', signature: 'CEILING(number, significance)', detail: 'Rounds a number up, away from zero.' },
  { name: 'COS', signature: 'COS(number)', detail: 'Returns the cosine of a given angle.' },
  { name: 'COSH', signature: 'COSH(number)', detail: 'Returns the hyperbolic cosine of a number.' },
  { name: 'EXP', signature: 'EXP(number)', detail: 'Returns e raised to the power of a given number.' },
  { name: 'FLOOR', signature: 'FLOOR(number, significance)', detail: 'Rounds a number down, toward zero.' },
  { name: 'INT', signature: 'INT(number)', detail: 'Rounds a number down to the nearest integer.' },
  { name: 'LN', signature: 'LN(number)', detail: 'Returns the natural logarithm of a number.' },
  { name: 'LOG', signature: 'LOG(number, [base])', detail: 'Returns the logarithm of a number to a specified base.' },
  { name: 'LOG10', signature: 'LOG10(number)', detail: 'Returns the base-10 logarithm of a number.' },
  { name: 'PI', signature: 'PI()', detail: 'Returns the number 3.14159265358979, the mathematical constant pi.' },
  { name: 'POWER', signature: 'POWER(number, power)', detail: 'Returns the result of a number raised to a power.' },
  { name: 'RAND', signature: 'RAND()', detail: 'Returns a random number between 0 and 1.' },
  { name: 'RANDBETWEEN', signature: 'RANDBETWEEN(bottom, top)', detail: 'Returns a random integer between the numbers you specify.' },
  { name: 'ROUND', signature: 'ROUND(number, [num_digits])', detail: 'Rounds a number to a specified number of digits.' },
  { name: 'SIGN', signature: 'SIGN(number)', detail: 'Determines the sign of a number. Returns 1 if positive, 0 if zero, and -1 if negative.' },
  { name: 'SIN', signature: 'SIN(number)', detail: 'Returns the sine of a given angle.' },
  { name: 'SINH', signature: 'SINH(number)', detail: 'Returns the hyperbolic sine of a number.' },
  { name: 'SQRT', signature: 'SQRT(number)', detail: 'Returns a positive square root.' },
  { name: 'SUM', signature: 'SUM(number1, [number2], ...)', detail: 'Adds all the numbers you specify as arguments.' },
  { name: 'TAN', signature: 'TAN(number)', detail: 'Returns the tangent of a given angle.' },
  { name: 'TANH', signature: 'TANH(number)', detail: 'Returns the hyperbolic tangent of a number.' },
  { name: 'TRUNC', signature: 'TRUNC(number, num_digits)', detail: 'Truncates a number to an integer by removing the fractional part of the number.' },

  // === Logical Functions ===
  { name: 'AND', signature: 'AND(logical1, [logical2], ...)', detail: 'Returns TRUE if all arguments are true.' },
  { name: 'OR', signature: 'OR(logical1, [logical2], ...)', detail: 'Returns TRUE if any argument is true.' },
  { name: 'NOT', signature: 'NOT(logical)', detail: 'Reverses the logic of its argument.' },
  { name: 'IF', signature: 'IF(logical_test, value_if_true, [value_if_false])', detail: 'Specifies a logical test to perform.' },
  { name: 'TRUE', signature: 'TRUE()', detail: 'Returns the logical value TRUE.' },
  { name: 'FALSE', signature: 'FALSE()', detail: 'Returns the logical value FALSE.' }
];

module.exports = FUNCTION_ITEMS;
